spring:
  data:
    mongodb:
      uri: mongodb+srv://skjalal:${PASSWORD}@mongoatlas.ors9s0n.mongodb.net/admin?retryWrites=true&replicaSet=atlas-f268rs-shard-0&readPreference=primary&srvServiceName=mongodb&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      database: sample_restaurants