spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/admin?retryWrites=true&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
      database: sample_restaurants